import re
from pathlib import Path
from readline import add_history


def get_tools_info_data(tools_dir: Path) -> list[dict]:
    tools_info = []
    for tool_script in tools_dir.iterdir():
        if not tool_script.is_file() or not tool_script.suffix == ".py":
            continue

        description = re.search(r'"""([\s\S]*?)"""', tool_script.read_text())
        if description:
            description = description.group(1).strip()
        else:
            description = "Not documented"

        tool_data = {
            "name": tool_script.stem,
            "path": str(tool_script),
            "description": description,
        }
        tools_info.append(tool_data)
    return tools_info


def generate_markdown(tools_info: list[dict]) -> str:
    markdown = "# list\n\n"
    for tool in tools_info:
        markdown += f"- [{tool['name']}]({tool['path']})\n\t- {tool['description']}\n"
    return markdown


def save_markdown(markdown: str, output_path: Path):
    output_path.write_text(markdown)


def add_to_readme(markdown: str, readme_path: Path):
    readme_content = readme_path.read_text()

    marker = "<!-- tools list generated by generate_tools_info.py -->"

    pattern = rf"{re.escape(marker)}.*\Z"
    replacement = f"{marker}\n{markdown}\n"

    updated_content = re.sub(
        pattern,
        replacement,
        readme_content,
        flags=re.DOTALL,
    )

    readme_path.write_text(updated_content)


if __name__ == "__main__":
    tools_dir = Path("tools")
    tools_markdown = Path("tools.md")
    readme_markdown = Path("README.md")

    tool_data = get_tools_info_data(tools_dir)
    markdown = generate_markdown(tool_data)

    save_markdown(markdown, tools_markdown)
    add_to_readme(markdown, readme_markdown)
